//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DBEntity
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class mc_dbEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“mc_dbEntities”部分中的连接字符串初始化新 mc_dbEntities 对象。
        /// </summary>
        public mc_dbEntities() : base("name=mc_dbEntities", "mc_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 mc_dbEntities 对象。
        /// </summary>
        public mc_dbEntities(string connectionString) : base(connectionString, "mc_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 mc_dbEntities 对象。
        /// </summary>
        public mc_dbEntities(EntityConnection connection) : base(connection, "mc_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<meeting_info> meeting_info
        {
            get
            {
                if ((_meeting_info == null))
                {
                    _meeting_info = base.CreateObjectSet<meeting_info>("meeting_info");
                }
                return _meeting_info;
            }
        }
        private ObjectSet<meeting_info> _meeting_info;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 meeting_info EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomeeting_info(meeting_info meeting_info)
        {
            base.AddObject("meeting_info", meeting_info);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MCDBModel", Name="meeting_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class meeting_info : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 meeting_info 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="m_title">m_title 属性的初始值。</param>
        /// <param name="m_position">m_position 属性的初始值。</param>
        /// <param name="m_people">m_people 属性的初始值。</param>
        /// <param name="m_start_time">m_start_time 属性的初始值。</param>
        /// <param name="m_end_time">m_end_time 属性的初始值。</param>
        /// <param name="m_level">m_level 属性的初始值。</param>
        /// <param name="m_creator">m_creator 属性的初始值。</param>
        /// <param name="m_create_time">m_create_time 属性的初始值。</param>
        public static meeting_info Createmeeting_info(global::System.Int32 id, global::System.String m_title, global::System.Int32 m_position, global::System.String m_people, global::System.DateTime m_start_time, global::System.DateTime m_end_time, global::System.Int32 m_level, global::System.String m_creator, global::System.DateTime m_create_time)
        {
            meeting_info meeting_info = new meeting_info();
            meeting_info.id = id;
            meeting_info.m_title = m_title;
            meeting_info.m_position = m_position;
            meeting_info.m_people = m_people;
            meeting_info.m_start_time = m_start_time;
            meeting_info.m_end_time = m_end_time;
            meeting_info.m_level = m_level;
            meeting_info.m_creator = m_creator;
            meeting_info.m_create_time = m_create_time;
            return meeting_info;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_title
        {
            get
            {
                return _m_title;
            }
            set
            {
                Onm_titleChanging(value);
                ReportPropertyChanging("m_title");
                _m_title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("m_title");
                Onm_titleChanged();
            }
        }
        private global::System.String _m_title;
        partial void Onm_titleChanging(global::System.String value);
        partial void Onm_titleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 m_position
        {
            get
            {
                return _m_position;
            }
            set
            {
                Onm_positionChanging(value);
                ReportPropertyChanging("m_position");
                _m_position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("m_position");
                Onm_positionChanged();
            }
        }
        private global::System.Int32 _m_position;
        partial void Onm_positionChanging(global::System.Int32 value);
        partial void Onm_positionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_people
        {
            get
            {
                return _m_people;
            }
            set
            {
                Onm_peopleChanging(value);
                ReportPropertyChanging("m_people");
                _m_people = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("m_people");
                Onm_peopleChanged();
            }
        }
        private global::System.String _m_people;
        partial void Onm_peopleChanging(global::System.String value);
        partial void Onm_peopleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime m_start_time
        {
            get
            {
                return _m_start_time;
            }
            set
            {
                Onm_start_timeChanging(value);
                ReportPropertyChanging("m_start_time");
                _m_start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("m_start_time");
                Onm_start_timeChanged();
            }
        }
        private global::System.DateTime _m_start_time;
        partial void Onm_start_timeChanging(global::System.DateTime value);
        partial void Onm_start_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime m_end_time
        {
            get
            {
                return _m_end_time;
            }
            set
            {
                Onm_end_timeChanging(value);
                ReportPropertyChanging("m_end_time");
                _m_end_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("m_end_time");
                Onm_end_timeChanged();
            }
        }
        private global::System.DateTime _m_end_time;
        partial void Onm_end_timeChanging(global::System.DateTime value);
        partial void Onm_end_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 m_level
        {
            get
            {
                return _m_level;
            }
            set
            {
                Onm_levelChanging(value);
                ReportPropertyChanging("m_level");
                _m_level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("m_level");
                Onm_levelChanged();
            }
        }
        private global::System.Int32 _m_level;
        partial void Onm_levelChanging(global::System.Int32 value);
        partial void Onm_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_creator
        {
            get
            {
                return _m_creator;
            }
            set
            {
                Onm_creatorChanging(value);
                ReportPropertyChanging("m_creator");
                _m_creator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("m_creator");
                Onm_creatorChanged();
            }
        }
        private global::System.String _m_creator;
        partial void Onm_creatorChanging(global::System.String value);
        partial void Onm_creatorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime m_create_time
        {
            get
            {
                return _m_create_time;
            }
            set
            {
                Onm_create_timeChanging(value);
                ReportPropertyChanging("m_create_time");
                _m_create_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("m_create_time");
                Onm_create_timeChanged();
            }
        }
        private global::System.DateTime _m_create_time;
        partial void Onm_create_timeChanging(global::System.DateTime value);
        partial void Onm_create_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String m_memo
        {
            get
            {
                return _m_memo;
            }
            set
            {
                Onm_memoChanging(value);
                ReportPropertyChanging("m_memo");
                _m_memo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("m_memo");
                Onm_memoChanged();
            }
        }
        private global::System.String _m_memo;
        partial void Onm_memoChanging(global::System.String value);
        partial void Onm_memoChanged();

        #endregion

    
    }

    #endregion

    
}
