//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("MCDBModel", "meeting_info_ibfk_1", "meeting_position", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBEntity.meeting_position), "meeting_info", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBEntity.meeting_info), true)]
[assembly: EdmRelationshipAttribute("MCDBModel", "meeting_info_ibfk_2", "user_info", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBEntity.user_info), "meeting_info", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBEntity.meeting_info), true)]
[assembly: EdmRelationshipAttribute("MCDBModel", "user_info_ibfk_1", "user_grade_catg", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBEntity.user_grade_catg), "user_info", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBEntity.user_info), true)]

#endregion

namespace DBEntity
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class mc_dbEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“mc_dbEntities”部分中的连接字符串初始化新 mc_dbEntities 对象。
        /// </summary>
        public mc_dbEntities() : base("name=mc_dbEntities", "mc_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 mc_dbEntities 对象。
        /// </summary>
        public mc_dbEntities(string connectionString) : base(connectionString, "mc_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 mc_dbEntities 对象。
        /// </summary>
        public mc_dbEntities(EntityConnection connection) : base(connection, "mc_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<meeting_info> meeting_info
        {
            get
            {
                if ((_meeting_info == null))
                {
                    _meeting_info = base.CreateObjectSet<meeting_info>("meeting_info");
                }
                return _meeting_info;
            }
        }
        private ObjectSet<meeting_info> _meeting_info;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<meeting_position> meeting_position
        {
            get
            {
                if ((_meeting_position == null))
                {
                    _meeting_position = base.CreateObjectSet<meeting_position>("meeting_position");
                }
                return _meeting_position;
            }
        }
        private ObjectSet<meeting_position> _meeting_position;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<user_grade_catg> user_grade_catg
        {
            get
            {
                if ((_user_grade_catg == null))
                {
                    _user_grade_catg = base.CreateObjectSet<user_grade_catg>("user_grade_catg");
                }
                return _user_grade_catg;
            }
        }
        private ObjectSet<user_grade_catg> _user_grade_catg;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<user_info> user_info
        {
            get
            {
                if ((_user_info == null))
                {
                    _user_info = base.CreateObjectSet<user_info>("user_info");
                }
                return _user_info;
            }
        }
        private ObjectSet<user_info> _user_info;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<user_info_detail> user_info_detail
        {
            get
            {
                if ((_user_info_detail == null))
                {
                    _user_info_detail = base.CreateObjectSet<user_info_detail>("user_info_detail");
                }
                return _user_info_detail;
            }
        }
        private ObjectSet<user_info_detail> _user_info_detail;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 meeting_info EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomeeting_info(meeting_info meeting_info)
        {
            base.AddObject("meeting_info", meeting_info);
        }
    
        /// <summary>
        /// 用于向 meeting_position EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomeeting_position(meeting_position meeting_position)
        {
            base.AddObject("meeting_position", meeting_position);
        }
    
        /// <summary>
        /// 用于向 user_grade_catg EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouser_grade_catg(user_grade_catg user_grade_catg)
        {
            base.AddObject("user_grade_catg", user_grade_catg);
        }
    
        /// <summary>
        /// 用于向 user_info EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouser_info(user_info user_info)
        {
            base.AddObject("user_info", user_info);
        }
    
        /// <summary>
        /// 用于向 user_info_detail EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouser_info_detail(user_info_detail user_info_detail)
        {
            base.AddObject("user_info_detail", user_info_detail);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MCDBModel", Name="meeting_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class meeting_info : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 meeting_info 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="mi_title">mi_title 属性的初始值。</param>
        /// <param name="mi_position">mi_position 属性的初始值。</param>
        /// <param name="mi_start_time">mi_start_time 属性的初始值。</param>
        /// <param name="mi_end_time">mi_end_time 属性的初始值。</param>
        /// <param name="mi_level">mi_level 属性的初始值。</param>
        /// <param name="mi_creator">mi_creator 属性的初始值。</param>
        /// <param name="mi_create_time">mi_create_time 属性的初始值。</param>
        public static meeting_info Createmeeting_info(global::System.Int32 id, global::System.String mi_title, global::System.Int16 mi_position, global::System.DateTime mi_start_time, global::System.DateTime mi_end_time, global::System.Int32 mi_level, global::System.Int16 mi_creator, global::System.DateTime mi_create_time)
        {
            meeting_info meeting_info = new meeting_info();
            meeting_info.id = id;
            meeting_info.mi_title = mi_title;
            meeting_info.mi_position = mi_position;
            meeting_info.mi_start_time = mi_start_time;
            meeting_info.mi_end_time = mi_end_time;
            meeting_info.mi_level = mi_level;
            meeting_info.mi_creator = mi_creator;
            meeting_info.mi_create_time = mi_create_time;
            return meeting_info;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mi_title
        {
            get
            {
                return _mi_title;
            }
            set
            {
                Onmi_titleChanging(value);
                ReportPropertyChanging("mi_title");
                _mi_title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mi_title");
                Onmi_titleChanged();
            }
        }
        private global::System.String _mi_title;
        partial void Onmi_titleChanging(global::System.String value);
        partial void Onmi_titleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 mi_position
        {
            get
            {
                return _mi_position;
            }
            set
            {
                Onmi_positionChanging(value);
                ReportPropertyChanging("mi_position");
                _mi_position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mi_position");
                Onmi_positionChanged();
            }
        }
        private global::System.Int16 _mi_position;
        partial void Onmi_positionChanging(global::System.Int16 value);
        partial void Onmi_positionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mi_people
        {
            get
            {
                return _mi_people;
            }
            set
            {
                Onmi_peopleChanging(value);
                ReportPropertyChanging("mi_people");
                _mi_people = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mi_people");
                Onmi_peopleChanged();
            }
        }
        private global::System.String _mi_people;
        partial void Onmi_peopleChanging(global::System.String value);
        partial void Onmi_peopleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime mi_start_time
        {
            get
            {
                return _mi_start_time;
            }
            set
            {
                Onmi_start_timeChanging(value);
                ReportPropertyChanging("mi_start_time");
                _mi_start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mi_start_time");
                Onmi_start_timeChanged();
            }
        }
        private global::System.DateTime _mi_start_time;
        partial void Onmi_start_timeChanging(global::System.DateTime value);
        partial void Onmi_start_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime mi_end_time
        {
            get
            {
                return _mi_end_time;
            }
            set
            {
                Onmi_end_timeChanging(value);
                ReportPropertyChanging("mi_end_time");
                _mi_end_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mi_end_time");
                Onmi_end_timeChanged();
            }
        }
        private global::System.DateTime _mi_end_time;
        partial void Onmi_end_timeChanging(global::System.DateTime value);
        partial void Onmi_end_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mi_level
        {
            get
            {
                return _mi_level;
            }
            set
            {
                Onmi_levelChanging(value);
                ReportPropertyChanging("mi_level");
                _mi_level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mi_level");
                Onmi_levelChanged();
            }
        }
        private global::System.Int32 _mi_level;
        partial void Onmi_levelChanging(global::System.Int32 value);
        partial void Onmi_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 mi_creator
        {
            get
            {
                return _mi_creator;
            }
            set
            {
                Onmi_creatorChanging(value);
                ReportPropertyChanging("mi_creator");
                _mi_creator = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mi_creator");
                Onmi_creatorChanged();
            }
        }
        private global::System.Int16 _mi_creator;
        partial void Onmi_creatorChanging(global::System.Int16 value);
        partial void Onmi_creatorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime mi_create_time
        {
            get
            {
                return _mi_create_time;
            }
            set
            {
                Onmi_create_timeChanging(value);
                ReportPropertyChanging("mi_create_time");
                _mi_create_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mi_create_time");
                Onmi_create_timeChanged();
            }
        }
        private global::System.DateTime _mi_create_time;
        partial void Onmi_create_timeChanging(global::System.DateTime value);
        partial void Onmi_create_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mi_memo
        {
            get
            {
                return _mi_memo;
            }
            set
            {
                Onmi_memoChanging(value);
                ReportPropertyChanging("mi_memo");
                _mi_memo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mi_memo");
                Onmi_memoChanged();
            }
        }
        private global::System.String _mi_memo;
        partial void Onmi_memoChanging(global::System.String value);
        partial void Onmi_memoChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MCDBModel", "meeting_info_ibfk_1", "meeting_position")]
        public meeting_position meeting_position
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<meeting_position>("MCDBModel.meeting_info_ibfk_1", "meeting_position").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<meeting_position>("MCDBModel.meeting_info_ibfk_1", "meeting_position").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<meeting_position> meeting_positionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<meeting_position>("MCDBModel.meeting_info_ibfk_1", "meeting_position");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<meeting_position>("MCDBModel.meeting_info_ibfk_1", "meeting_position", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MCDBModel", "meeting_info_ibfk_2", "user_info")]
        public user_info user_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_info>("MCDBModel.meeting_info_ibfk_2", "user_info").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_info>("MCDBModel.meeting_info_ibfk_2", "user_info").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user_info> user_infoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_info>("MCDBModel.meeting_info_ibfk_2", "user_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user_info>("MCDBModel.meeting_info_ibfk_2", "user_info", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MCDBModel", Name="meeting_position")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class meeting_position : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 meeting_position 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="mp_name">mp_name 属性的初始值。</param>
        /// <param name="mp_size">mp_size 属性的初始值。</param>
        public static meeting_position Createmeeting_position(global::System.Int16 id, global::System.String mp_name, global::System.SByte mp_size)
        {
            meeting_position meeting_position = new meeting_position();
            meeting_position.id = id;
            meeting_position.mp_name = mp_name;
            meeting_position.mp_size = mp_size;
            return meeting_position;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int16 _id;
        partial void OnidChanging(global::System.Int16 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mp_name
        {
            get
            {
                return _mp_name;
            }
            set
            {
                Onmp_nameChanging(value);
                ReportPropertyChanging("mp_name");
                _mp_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mp_name");
                Onmp_nameChanged();
            }
        }
        private global::System.String _mp_name;
        partial void Onmp_nameChanging(global::System.String value);
        partial void Onmp_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte mp_size
        {
            get
            {
                return _mp_size;
            }
            set
            {
                Onmp_sizeChanging(value);
                ReportPropertyChanging("mp_size");
                _mp_size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mp_size");
                Onmp_sizeChanged();
            }
        }
        private global::System.SByte _mp_size;
        partial void Onmp_sizeChanging(global::System.SByte value);
        partial void Onmp_sizeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MCDBModel", "meeting_info_ibfk_1", "meeting_info")]
        public EntityCollection<meeting_info> meeting_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<meeting_info>("MCDBModel.meeting_info_ibfk_1", "meeting_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<meeting_info>("MCDBModel.meeting_info_ibfk_1", "meeting_info", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MCDBModel", Name="user_grade_catg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_grade_catg : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 user_grade_catg 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="gc_level">gc_level 属性的初始值。</param>
        /// <param name="gc_name">gc_name 属性的初始值。</param>
        public static user_grade_catg Createuser_grade_catg(global::System.SByte id, global::System.SByte gc_level, global::System.String gc_name)
        {
            user_grade_catg user_grade_catg = new user_grade_catg();
            user_grade_catg.id = id;
            user_grade_catg.gc_level = gc_level;
            user_grade_catg.gc_name = gc_name;
            return user_grade_catg;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.SByte _id;
        partial void OnidChanging(global::System.SByte value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte gc_level
        {
            get
            {
                return _gc_level;
            }
            set
            {
                Ongc_levelChanging(value);
                ReportPropertyChanging("gc_level");
                _gc_level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gc_level");
                Ongc_levelChanged();
            }
        }
        private global::System.SByte _gc_level;
        partial void Ongc_levelChanging(global::System.SByte value);
        partial void Ongc_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gc_name
        {
            get
            {
                return _gc_name;
            }
            set
            {
                Ongc_nameChanging(value);
                ReportPropertyChanging("gc_name");
                _gc_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gc_name");
                Ongc_nameChanged();
            }
        }
        private global::System.String _gc_name;
        partial void Ongc_nameChanging(global::System.String value);
        partial void Ongc_nameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MCDBModel", "user_info_ibfk_1", "user_info")]
        public EntityCollection<user_info> user_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_info>("MCDBModel.user_info_ibfk_1", "user_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_info>("MCDBModel.user_info_ibfk_1", "user_info", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MCDBModel", Name="user_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_info : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 user_info 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="ui_name">ui_name 属性的初始值。</param>
        /// <param name="ui_password">ui_password 属性的初始值。</param>
        /// <param name="ui_email">ui_email 属性的初始值。</param>
        /// <param name="ui_grade_id">ui_grade_id 属性的初始值。</param>
        /// <param name="ui_gender">ui_gender 属性的初始值。</param>
        /// <param name="ui_status">ui_status 属性的初始值。</param>
        /// <param name="ui_create_time">ui_create_time 属性的初始值。</param>
        public static user_info Createuser_info(global::System.Int16 id, global::System.String ui_name, global::System.String ui_password, global::System.String ui_email, global::System.SByte ui_grade_id, global::System.Boolean ui_gender, global::System.Boolean ui_status, global::System.DateTime ui_create_time)
        {
            user_info user_info = new user_info();
            user_info.id = id;
            user_info.ui_name = ui_name;
            user_info.ui_password = ui_password;
            user_info.ui_email = ui_email;
            user_info.ui_grade_id = ui_grade_id;
            user_info.ui_gender = ui_gender;
            user_info.ui_status = ui_status;
            user_info.ui_create_time = ui_create_time;
            return user_info;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int16 _id;
        partial void OnidChanging(global::System.Int16 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ui_name
        {
            get
            {
                return _ui_name;
            }
            set
            {
                Onui_nameChanging(value);
                ReportPropertyChanging("ui_name");
                _ui_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ui_name");
                Onui_nameChanged();
            }
        }
        private global::System.String _ui_name;
        partial void Onui_nameChanging(global::System.String value);
        partial void Onui_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ui_password
        {
            get
            {
                return _ui_password;
            }
            set
            {
                Onui_passwordChanging(value);
                ReportPropertyChanging("ui_password");
                _ui_password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ui_password");
                Onui_passwordChanged();
            }
        }
        private global::System.String _ui_password;
        partial void Onui_passwordChanging(global::System.String value);
        partial void Onui_passwordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ui_email
        {
            get
            {
                return _ui_email;
            }
            set
            {
                Onui_emailChanging(value);
                ReportPropertyChanging("ui_email");
                _ui_email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ui_email");
                Onui_emailChanged();
            }
        }
        private global::System.String _ui_email;
        partial void Onui_emailChanging(global::System.String value);
        partial void Onui_emailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte ui_grade_id
        {
            get
            {
                return _ui_grade_id;
            }
            set
            {
                Onui_grade_idChanging(value);
                ReportPropertyChanging("ui_grade_id");
                _ui_grade_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ui_grade_id");
                Onui_grade_idChanged();
            }
        }
        private global::System.SByte _ui_grade_id;
        partial void Onui_grade_idChanging(global::System.SByte value);
        partial void Onui_grade_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ui_gender
        {
            get
            {
                return _ui_gender;
            }
            set
            {
                Onui_genderChanging(value);
                ReportPropertyChanging("ui_gender");
                _ui_gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ui_gender");
                Onui_genderChanged();
            }
        }
        private global::System.Boolean _ui_gender;
        partial void Onui_genderChanging(global::System.Boolean value);
        partial void Onui_genderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ui_status
        {
            get
            {
                return _ui_status;
            }
            set
            {
                Onui_statusChanging(value);
                ReportPropertyChanging("ui_status");
                _ui_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ui_status");
                Onui_statusChanged();
            }
        }
        private global::System.Boolean _ui_status;
        partial void Onui_statusChanging(global::System.Boolean value);
        partial void Onui_statusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ui_create_time
        {
            get
            {
                return _ui_create_time;
            }
            set
            {
                Onui_create_timeChanging(value);
                ReportPropertyChanging("ui_create_time");
                _ui_create_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ui_create_time");
                Onui_create_timeChanged();
            }
        }
        private global::System.DateTime _ui_create_time;
        partial void Onui_create_timeChanging(global::System.DateTime value);
        partial void Onui_create_timeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MCDBModel", "meeting_info_ibfk_2", "meeting_info")]
        public EntityCollection<meeting_info> meeting_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<meeting_info>("MCDBModel.meeting_info_ibfk_2", "meeting_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<meeting_info>("MCDBModel.meeting_info_ibfk_2", "meeting_info", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MCDBModel", "user_info_ibfk_1", "user_grade_catg")]
        public user_grade_catg user_grade_catg
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_grade_catg>("MCDBModel.user_info_ibfk_1", "user_grade_catg").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_grade_catg>("MCDBModel.user_info_ibfk_1", "user_grade_catg").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user_grade_catg> user_grade_catgReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user_grade_catg>("MCDBModel.user_info_ibfk_1", "user_grade_catg");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user_grade_catg>("MCDBModel.user_info_ibfk_1", "user_grade_catg", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MCDBModel", Name="user_info_detail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_info_detail : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 user_info_detail 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="ui_name">ui_name 属性的初始值。</param>
        /// <param name="ui_password">ui_password 属性的初始值。</param>
        /// <param name="ui_email">ui_email 属性的初始值。</param>
        /// <param name="ui_grade_id">ui_grade_id 属性的初始值。</param>
        /// <param name="ui_gender">ui_gender 属性的初始值。</param>
        /// <param name="ui_status">ui_status 属性的初始值。</param>
        /// <param name="ui_create_time">ui_create_time 属性的初始值。</param>
        /// <param name="ui_grade_level">ui_grade_level 属性的初始值。</param>
        /// <param name="ui_grade_name">ui_grade_name 属性的初始值。</param>
        public static user_info_detail Createuser_info_detail(global::System.Int16 id, global::System.String ui_name, global::System.String ui_password, global::System.String ui_email, global::System.SByte ui_grade_id, global::System.Boolean ui_gender, global::System.Boolean ui_status, global::System.DateTime ui_create_time, global::System.SByte ui_grade_level, global::System.String ui_grade_name)
        {
            user_info_detail user_info_detail = new user_info_detail();
            user_info_detail.id = id;
            user_info_detail.ui_name = ui_name;
            user_info_detail.ui_password = ui_password;
            user_info_detail.ui_email = ui_email;
            user_info_detail.ui_grade_id = ui_grade_id;
            user_info_detail.ui_gender = ui_gender;
            user_info_detail.ui_status = ui_status;
            user_info_detail.ui_create_time = ui_create_time;
            user_info_detail.ui_grade_level = ui_grade_level;
            user_info_detail.ui_grade_name = ui_grade_name;
            return user_info_detail;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int16 _id;
        partial void OnidChanging(global::System.Int16 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ui_name
        {
            get
            {
                return _ui_name;
            }
            set
            {
                if (_ui_name != value)
                {
                    Onui_nameChanging(value);
                    ReportPropertyChanging("ui_name");
                    _ui_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ui_name");
                    Onui_nameChanged();
                }
            }
        }
        private global::System.String _ui_name;
        partial void Onui_nameChanging(global::System.String value);
        partial void Onui_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ui_password
        {
            get
            {
                return _ui_password;
            }
            set
            {
                if (_ui_password != value)
                {
                    Onui_passwordChanging(value);
                    ReportPropertyChanging("ui_password");
                    _ui_password = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ui_password");
                    Onui_passwordChanged();
                }
            }
        }
        private global::System.String _ui_password;
        partial void Onui_passwordChanging(global::System.String value);
        partial void Onui_passwordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ui_email
        {
            get
            {
                return _ui_email;
            }
            set
            {
                if (_ui_email != value)
                {
                    Onui_emailChanging(value);
                    ReportPropertyChanging("ui_email");
                    _ui_email = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ui_email");
                    Onui_emailChanged();
                }
            }
        }
        private global::System.String _ui_email;
        partial void Onui_emailChanging(global::System.String value);
        partial void Onui_emailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte ui_grade_id
        {
            get
            {
                return _ui_grade_id;
            }
            set
            {
                if (_ui_grade_id != value)
                {
                    Onui_grade_idChanging(value);
                    ReportPropertyChanging("ui_grade_id");
                    _ui_grade_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ui_grade_id");
                    Onui_grade_idChanged();
                }
            }
        }
        private global::System.SByte _ui_grade_id;
        partial void Onui_grade_idChanging(global::System.SByte value);
        partial void Onui_grade_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ui_gender
        {
            get
            {
                return _ui_gender;
            }
            set
            {
                if (_ui_gender != value)
                {
                    Onui_genderChanging(value);
                    ReportPropertyChanging("ui_gender");
                    _ui_gender = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ui_gender");
                    Onui_genderChanged();
                }
            }
        }
        private global::System.Boolean _ui_gender;
        partial void Onui_genderChanging(global::System.Boolean value);
        partial void Onui_genderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ui_status
        {
            get
            {
                return _ui_status;
            }
            set
            {
                if (_ui_status != value)
                {
                    Onui_statusChanging(value);
                    ReportPropertyChanging("ui_status");
                    _ui_status = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ui_status");
                    Onui_statusChanged();
                }
            }
        }
        private global::System.Boolean _ui_status;
        partial void Onui_statusChanging(global::System.Boolean value);
        partial void Onui_statusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ui_create_time
        {
            get
            {
                return _ui_create_time;
            }
            set
            {
                if (_ui_create_time != value)
                {
                    Onui_create_timeChanging(value);
                    ReportPropertyChanging("ui_create_time");
                    _ui_create_time = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ui_create_time");
                    Onui_create_timeChanged();
                }
            }
        }
        private global::System.DateTime _ui_create_time;
        partial void Onui_create_timeChanging(global::System.DateTime value);
        partial void Onui_create_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte ui_grade_level
        {
            get
            {
                return _ui_grade_level;
            }
            set
            {
                if (_ui_grade_level != value)
                {
                    Onui_grade_levelChanging(value);
                    ReportPropertyChanging("ui_grade_level");
                    _ui_grade_level = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ui_grade_level");
                    Onui_grade_levelChanged();
                }
            }
        }
        private global::System.SByte _ui_grade_level;
        partial void Onui_grade_levelChanging(global::System.SByte value);
        partial void Onui_grade_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ui_grade_name
        {
            get
            {
                return _ui_grade_name;
            }
            set
            {
                if (_ui_grade_name != value)
                {
                    Onui_grade_nameChanging(value);
                    ReportPropertyChanging("ui_grade_name");
                    _ui_grade_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ui_grade_name");
                    Onui_grade_nameChanged();
                }
            }
        }
        private global::System.String _ui_grade_name;
        partial void Onui_grade_nameChanging(global::System.String value);
        partial void Onui_grade_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ui_meeting_count
        {
            get
            {
                return _ui_meeting_count;
            }
            set
            {
                Onui_meeting_countChanging(value);
                ReportPropertyChanging("ui_meeting_count");
                _ui_meeting_count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ui_meeting_count");
                Onui_meeting_countChanged();
            }
        }
        private Nullable<global::System.Int64> _ui_meeting_count;
        partial void Onui_meeting_countChanging(Nullable<global::System.Int64> value);
        partial void Onui_meeting_countChanged();

        #endregion

    
    }

    #endregion

    
}
